# Generated by Django 4.2.1 on 2023-05-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_alter_course_id_alter_enrollment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
    ]
